AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  wisdom-http-api

Parameters:
  StageName:
    Type: String
    Description: first path segment of URI
    Default: v0
  UserPoolId:
    Type: String
    Description: Cognito User Pool ID for authencation
  ContentGitRepositoryURL:
    Type: String
    Description: Git repository URL of wisdom-content (e.g., git@github.com:KoharaKazuya/wisdom-content.git)

Globals:
  Function:
    Timeout: 60

Resources:
  ServerApi:
    Type: AWS::Serverless::Api
    Properties:
      EndpointConfiguration:
        Type: REGIONAL
      StageName: !Ref StageName
      Auth:
        ApiKeyRequired: true
        UsagePlan:
          UsagePlanName: CloudFront (wisdom-cloud/cdn-with-auth)
          CreateUsagePlan: PER_API

  ServerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: server/
      Handler: server
      Runtime: go1.x
      Events:
        CatchAll:
          Type: Api
          Properties:
            RestApiId: !Ref ServerApi
            Path: /{proxy+}
            Method: ANY
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: wisdom/wisdom-http-api/deploy-key
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - cognito-idp:AdminGetUser
              Resource:
                - !Sub arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${UserPoolId}
      Environment:
        Variables:
          WISDOM_COGNITO_USER_POOL_ID: !Ref UserPoolId
          CONTENT_GIT_REPOSITORY_URL: !Ref ContentGitRepositoryURL

Outputs:
  ServerAPI:
    Description: "API Gateway endpoint URL for Prod environment for Server Function"
    Value: !Sub "https://${ServerApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/"
  ServerFunction:
    Description: "Server Lambda Function ARN"
    Value: !GetAtt ServerFunction.Arn
  ServerFunctionIamRole:
    Description: "Implicit IAM Role created for Server function"
    Value: !GetAtt ServerFunctionRole.Arn
